// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:2dc56887-3f5c-430f-8562-21ea129b261c",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_TFKbIv94F",
    "aws_user_pools_web_client_id": "6jf8o17qcr00dsk33a6gfoc1km"
};


export default awsmobile;
